# @file GeneratePDF.R
#
# Copyright 2025 Observational Health Data Sciences and Informatics
#
# This file is part of the DbDiagnostics package
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' createPdfReport

#' @param results DbDiagnostics results table
#' @param file Name and location for generated report, example: "./report.pdf"

#' @export

createPdfReport <- function(results, file) {
	tempRmd <- tempfile(fileext = ".Rmd")
	rmdContent <- '
---
title: "Database Diagnostics Report"
author: "Generated by DbDiagnostics"
date: "`r format(Sys.Date(), \'%B %d, %Y\')`"
output:
  pdf_document:
    latex_engine: xelatex
    toc: false
header-includes:
  - \\usepackage{colortbl}
  - \\usepackage{xcolor}
  - \\definecolor{pass}{RGB}{76,175,80}
  - \\definecolor{fail}{RGB}{244,67,54}
  - \\definecolor{na}{RGB}{204,204,204}
  - \\usepackage{float}
params:
  results: !r NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(knitr)
results <- params$results

if (!is.null(results)) {
  if ("proportion" %in% names(results)) {
    results$proportion <- as.numeric(as.character(results$proportion))
  }
  if ("value" %in% names(results)) {
    results$value <- as.numeric(as.character(results$value))
  }
}
```


\\pagebreak

\\begin{center}
\\Large\\textbf{Analysis Details}
\\end{center}

```{r analysis-details, results="asis"}
if (!is.null(results) && is.data.frame(results) && nrow(results) > 0 && "analysisName" %in% names(results)) {

  uniqueAnalyses <- unique(results$analysisName[!is.na(results$analysisName)])

  # T/C/I/O SECTION


  for (analysisName in uniqueAnalyses) {
    analysisEscaped <- gsub("_", "\\\\\\\\_", as.character(analysisName))
    cat("\\n\\\\subsection*{Analysis Name: ", analysisEscaped, "}\\n\\n", sep = "")

    analysisData <- results[!is.na(results$analysisName) & results$analysisName == analysisName, ]

    if ("databaseId" %in% names(analysisData)) {
      uniqueDbsAnalysis <- unique(analysisData$databaseId[!is.na(analysisData$databaseId)])

      if (length(uniqueDbsAnalysis) > 0) {
        conceptTypes <- list(
          Target = "propWithRequiredTargetConcepts",
          Comparator = "propWithRequiredComparatorConcepts",
          Indication = "propWithRequiredIndicationConcepts",
          Outcome = "propWithRequiredOutcomeConcepts"
        )

        cat("\\\\begin{table}[H]\\n")
        cat("\\\\centering\\n")
        cat("\\\\begin{tabular}{|l|c|c|c|c|}\\n")
        cat("\\\\hline\\n")
        cat("\\\\textbf{Database} & \\\\textbf{T} & \\\\textbf{C} & \\\\textbf{I} & \\\\textbf{O} \\\\\\\\\\n")
        cat("\\\\hline\\\\hline\\n")
        cat("\\\\hline\\n")

        passCount <- 0
        failCount <- 0
        naCount <- 0

        for (db in uniqueDbsAnalysis) {
          dbResults <- analysisData[!is.na(analysisData$databaseId) & analysisData$databaseId == db, ]

          dbEscaped <- gsub("_", "\\\\\\\\_", db)

          cat(dbEscaped, " & ")

          for (i in seq_along(conceptTypes)) {
            statisticName <- conceptTypes[[i]]

            cellColor <- "na"
            statRow <- data.frame()

            if ("statistic" %in% names(dbResults)) {
              statRow <- dbResults[!is.na(dbResults$statistic) &
                                      dbResults$statistic == statisticName, ]

              if (nrow(statRow) > 0 && "status" %in% names(statRow)) {
                statusVal <- statRow$status[1]
                if (!is.na(statusVal)) {
                  if (tolower(statusVal) == "pass") {
                    cellColor <- "pass"
                    passCount <- passCount + 1
                  } else if (tolower(statusVal) == "fail") {
                    cellColor <- "fail"
                    failCount <- failCount + 1
                  } else {
                    naCount <- naCount + 1
                  }
                } else {
                  naCount <- naCount + 1
                }
              } else {
                naCount <- naCount + 1
              }
            } else {
              naCount <- naCount + 1
            }

            propVal <- "N/A"
            if (nrow(statRow) > 0 && "proportion" %in% names(statRow) && !is.na(statRow$proportion[1])) {
              propVal <- paste0(round(statRow$proportion[1] * 100, 2), "\\\\%")
            }

            cat("\\\\cellcolor{", cellColor, "} ", propVal, sep = "")

            if (i < length(conceptTypes)) {
              cat(" & ")
            } else {
              cat(" \\\\\\\\\\n")
            }
          }
        }

        cat("\\\\hline\\n")
        cat("\\\\end{tabular}\\n")
        cat("\\\\end{table}\\n\\n")

        totalChecks <- length(uniqueDbsAnalysis) * length(conceptTypes)

       dbMeetAll <- 0
			 for (db in uniqueDbsAnalysis) {
	     dbResults <- analysisData[!is.na(analysisData$databaseId) & analysisData$databaseId == db, ]
	     meetsAll <- TRUE
			 for (statName in c("propWithRequiredTargetConcepts", "propWithRequiredComparatorConcepts",
													"propWithRequiredIndicationConcepts", "propWithRequiredOutcomeConcepts")) {
				statRow <- dbResults[!is.na(dbResults$statistic) & dbResults$statistic == statName, ]
				if (nrow(statRow) > 0 && "status" %in% names(statRow)) {
					statusVal <- statRow$status[1]
					if (is.na(statusVal)) {
						next
					}
					if (tolower(statusVal) != "pass") {
						meetsAll <- FALSE
						break
					}
				}
			}
			if (meetsAll) {
				dbMeetAll <- dbMeetAll + 1
			}
		}
				percentMeetAll <- ifelse(length(uniqueDbsAnalysis) > 0,
													 round((dbMeetAll / length(uniqueDbsAnalysis)) * 100, 2),
													 0)
				cat("\\\\noindent Percent of databases that meet all T/C/I/O: ", percentMeetAll, "\\\\%\\n\\n", sep = "")

        # COMPARATOR SECTION
        comparatorData <- analysisData[!is.na(analysisData$statistic) &
                                        analysisData$statistic == "propWithRequiredComparatorConcepts", ]

        if (nrow(comparatorData) > 0 && "spec" %in% names(comparatorData)) {
          compNames <- unique(comparatorData$spec[!is.na(comparatorData$spec)])

          if (length(compNames) > 0) {
            compName <- compNames[1]
            compEscaped <- gsub("_", "\\\\\\\\_", as.character(compName))

            cat("\\\\vspace{0.5cm}\\n")
            cat("\\\\noindent\\\\textbf{Comparator: ", compEscaped, "}\\n\\n", sep = "")

            compSubset <- comparatorData[!is.na(comparatorData$spec) & comparatorData$spec == compName, ]

            if (nrow(compSubset) > 0 && "databaseId" %in% names(compSubset)) {
              compSubset <- compSubset[order(compSubset$databaseId), ]

              cat("\\\\begin{table}[H]\\n")
              cat("\\\\centering\\n")
              cat("\\\\begin{tabular}{|l|r|r|}\\n")
              cat("\\\\hline\\n")
              cat("\\\\textbf{Database} & \\\\textbf{Count} & \\\\textbf{Proportion} \\\\\\\\\\n")
              cat("\\\\hline\\n")

              for (i in 1:nrow(compSubset)) {
                row <- compSubset[i, ]

                dbName <- ifelse(is.na(row$databaseId), "Unknown", as.character(row$databaseId))
                dbEscaped <- gsub("_", "\\\\\\\\_", dbName)

                countVal <- ifelse("value" %in% names(row) && !is.na(row$value),
                                  format(round(row$value), big.mark = ","),
                                  "N/A")

                if ("proportion" %in% names(row) && !is.na(row$proportion)) {
                  propVal <- paste0(round(row$proportion * 100, 2), "\\\\%")
                } else {
                  propVal <- "N/A"
                }

                cat(dbEscaped, " & ", countVal, " & ", propVal, " \\\\\\\\\\n", sep = "")
              }

              cat("\\\\hline\\n")
              cat("\\\\end{tabular}\\n")
              cat("\\\\end{table}\\n\\n")
            }
          }
        }

        # TARGET SECTION
        targetData <- analysisData[!is.na(analysisData$statistic) &
                                     analysisData$statistic == "propWithRequiredTargetConcepts", ]

        if (nrow(targetData) > 0 && "spec" %in% names(targetData)) {
          targetNames <- unique(targetData$spec[!is.na(targetData$spec)])

          if (length(targetNames) > 0) {
            for (targetName in targetNames) {
              targetEscaped <- gsub("_", "\\\\\\\\_", as.character(targetName))

              cat("\\\\vspace{0.5cm}\\n")
              cat("\\\\noindent\\\\textbf{Target: ", targetEscaped, "}\\n\\n", sep = "")

              targetSubset <- targetData[!is.na(targetData$spec) & targetData$spec == targetName, ]

              if (nrow(targetSubset) > 0 && "databaseId" %in% names(targetSubset)) {
                targetSubset <- targetSubset[order(targetSubset$databaseId), ]

                cat("\\\\begin{table}[H]\\n")
                cat("\\\\centering\\n")
                cat("\\\\begin{tabular}{|l|r|r|}\\n")
                cat("\\\\hline\\n")
                cat("\\\\textbf{Database} & \\\\textbf{Count} & \\\\textbf{Proportion} \\\\\\\\\\n")
                cat("\\\\hline\\n")

                for (i in 1:nrow(targetSubset)) {
                  row <- targetSubset[i, ]

                  dbName <- ifelse(is.na(row$databaseId), "Unknown", as.character(row$databaseId))
                  dbEscaped <- gsub("_", "\\\\\\\\_", dbName)

                  countVal <- ifelse("value" %in% names(row) && !is.na(row$value),
                                    format(round(row$value), big.mark = ","),
                                    "N/A")

                  if ("proportion" %in% names(row) && !is.na(row$proportion)) {
                    propVal <- paste0(round(row$proportion * 100, 2), "\\\\%")
                  } else {
                    propVal <- "N/A"
                  }

                  cat(dbEscaped, " & ", countVal, " & ", propVal, " \\\\\\\\\\n", sep = "")
                }

                cat("\\\\hline\\n")
                cat("\\\\end{tabular}\\n")
                cat("\\\\end{table}\\n\\n")
              }
            }
          }
        }

        # OUTCOME SECTION
        outcomeData <- analysisData[!is.na(analysisData$statistic) &
                                     analysisData$statistic == "propWithRequiredOutcomeConcepts", ]

        if (nrow(outcomeData) > 0 && "spec" %in% names(outcomeData)) {
          outcomeNames <- unique(outcomeData$spec[!is.na(outcomeData$spec)])

          if (length(outcomeNames) > 0) {
            for (outcomeName in outcomeNames) {
              outcomeEscaped <- gsub("_", "\\\\\\\\_", as.character(outcomeName))

              cat("\\\\vspace{0.5cm}\\n")
              cat("\\\\noindent\\\\textbf{Outcome: ", outcomeEscaped, "}\\n\\n", sep = "")

              outcomeAllStats <- analysisData[!is.na(analysisData$spec) &
                                                analysisData$spec == outcomeName, ]

              if ("databaseId" %in% names(outcomeAllStats)) {
                uniqueDbsOutcome <- unique(outcomeAllStats$databaseId[!is.na(outcomeAllStats$databaseId)])

                if (length(uniqueDbsOutcome) > 0) {
                  allOutcomeStats <- list(
                    "propWithRequiredOutcomeConcepts" = "Concepts",
                    "propWithERCriteria" = "ER",
                    "propMeasRecordsWithValues" = "Meas Values",
                    "propWithProcedureCriteria" = "Procedure",
                    "propWithObservationCriteria" = "Observation",
                    "propWithDeathCriteria" = "Death",
                    "propWithOPCriteria" = "OP",
                    "propWithMeasurementCriteria" = "Measurement",
                    "propWithIPCriteria" = "IP",
                    "propWithGenderCriteria" = "Gender",
                    "propWithEthnicityCriteria" = "Ethnicity",
                    "propWithDrugCriteria" = "Drug",
                    "propWithDeviceCriteria" = "Device",
                    "propWithConditionCriteria" = "Condition"
                  )

                  statsWithData <- c()
                  for (statName in names(allOutcomeStats)) {
                    statRows <- outcomeAllStats[!is.na(outcomeAllStats$statistic) &
                                                   outcomeAllStats$statistic == statName, ]
                    if (nrow(statRows) > 0) {
                      hasData <- FALSE
                      for (k in 1:nrow(statRows)) {
                        if (("status" %in% names(statRows) && !is.na(statRows$status[k])) ||
                            ("fail" %in% names(statRows) && !is.na(statRows$fail[k])) ||
                            ("proportion" %in% names(statRows) && !is.na(statRows$proportion[k]))) {
                          hasData <- TRUE
                          break
                        }
                      }
                      if (hasData) {
                        statsWithData <- c(statsWithData, statName)
                      }
                    }
                  }

                  if (length(statsWithData) > 0) {
                    numCols <- length(statsWithData) + 1
                    colSpec <- paste0("|l|", paste(rep("c|", length(statsWithData)), collapse = ""))

                    headerParts <- c("\\\\textbf{Database}")
                    for (statName in statsWithData) {
                      headerParts <- c(headerParts, paste0("\\\\textbf{", allOutcomeStats[[statName]], "}"))
                    }
                    headerRow <- paste(headerParts, collapse = " & ")



                    cat("\\\\begin{table}[H]\\n")
                    cat("\\\\centering\\n")
                    cat("\\\\resizebox{\\\\textwidth}{!}{%\\n")
                    cat("\\\\begin{tabular}{", colSpec, "}\\n", sep = "")
                    cat("\\\\hline\\n")
                    cat(headerRow, " \\\\\\\\\\n", sep = "")
                    cat("\\\\hline\\n")

                    for (db in uniqueDbsOutcome) {
                      dbOutcomeResults <- outcomeAllStats[!is.na(outcomeAllStats$databaseId) &
                                                             outcomeAllStats$databaseId == db, ]

                      dbEscaped <- gsub("_", "\\\\\\\\_", db)
                      cat(dbEscaped, " & ")

                      for (j in seq_along(statsWithData)) {
                        statName <- statsWithData[j]

                        cellColor <- "na"
                        cellText <- ""

                        if ("statistic" %in% names(dbOutcomeResults)) {
                          statRow <- dbOutcomeResults[!is.na(dbOutcomeResults$statistic) &
                                                        dbOutcomeResults$statistic == statName, ]

                          if (nrow(statRow) > 0) {
                            if ("status" %in% names(statRow) && !is.na(statRow$status[1])) {
                              statusVal <- statRow$status[1]
                              if (tolower(statusVal) == "pass") {
                                cellColor <- "pass"
                                if ("proportion" %in% names(statRow) && !is.na(statRow$proportion[1])) {
                                  cellText <- paste0(round(statRow$proportion[1] * 100, 2), "\\\\%")
                                }
                              } else if (tolower(statusVal) == "fail") {
                                cellColor <- "fail"
                                if ("proportion" %in% names(statRow) && !is.na(statRow$proportion[1])) {
                                  cellText <- paste0(round(statRow$proportion[1] * 100, 2), "\\\\%")
                                }
                              }
                            }

                            else if ("fail" %in% names(statRow) && !is.na(statRow$fail[1])) {
                              failVal <- statRow$fail[1]
                              if (failVal == 0) {
                                cellColor <- "pass"
                              } else if (failVal == 1) {
                                cellColor <- "fail"
                              } else {
                                cellText <- as.character(failVal)
                              }
                            }
                          }
                        }

                        cat("\\\\cellcolor{", cellColor, "} ", cellText, sep = "")

                        if (j < length(statsWithData)) {
                          cat(" & ")
                        } else {
                          cat(" \\\\\\\\\\n")
                        }
                      }
                    }

                    cat("\\\\hline\\n")
                    cat("\\\\end{tabular}%\\n")
                    cat("}\\n")
                    cat("\\\\end{table}\\n\\n")
                  }
                }
              }
            }
          }
        }

        # TARGET/COMPARATOR REQUIREMENTS SECTION
        cat("\\\\vspace{0.5cm}\\n")
        cat("\\\\noindent\\\\textbf{Target/Comparator Requirements}\\n\\n")

        if ("databaseId" %in% names(analysisData)) {
          uniqueDbsAnalysis <- unique(analysisData$databaseId[!is.na(analysisData$databaseId)])

          if (length(uniqueDbsAnalysis) > 0) {
            requirementStats <- c(
              "propWithCalendarTime",
              "propInAgeRange",
              "propWithAgeAtFirstObs",
              "propWithLongitudinalCriteria",
              "propWithRaceCriteria",
              "propWithRequiredDomain"
            )

            cat("\\\\begin{table}[H]\\n")
            cat("\\\\centering\\n")
            cat("\\\\resizebox{\\\\textwidth}{!}{%\\n")
            cat("\\\\begin{tabular}{|l|c|c|c|c|c|c|}\\n")
            cat("\\\\hline\\n")
            cat("\\\\textbf{Database} & \\\\textbf{Calendar Time} & \\\\textbf{Age Range} & \\\\textbf{Age at First Obs} & \\\\textbf{Longitudinal} & \\\\textbf{Race} & \\\\textbf{Domain} \\\\\\\\\\n")
            cat("\\\\hline\\n")

            for (db in uniqueDbsAnalysis) {
              dbAnalysisResults <- analysisData[!is.na(analysisData$databaseId) &
                                                  analysisData$databaseId == db, ]

              dbEscaped <- gsub("_", "\\\\\\\\_", db)
              cat(dbEscaped, " & ")

              for (j in seq_along(requirementStats)) {
                statName <- requirementStats[j]

                cellColor <- "na"

                if ("statistic" %in% names(dbAnalysisResults)) {
                  statRow <- dbAnalysisResults[!is.na(dbAnalysisResults$statistic) &
                                                 dbAnalysisResults$statistic == statName, ]

                  if (nrow(statRow) > 0 && "status" %in% names(statRow)) {
                    statusVal <- statRow$status[1]
                    if (!is.na(statusVal)) {
                      if (tolower(statusVal) == "pass") {
                        cellColor <- "pass"
                      } else if (tolower(statusVal) == "fail") {
                        cellColor <- "fail"
                      }
                    }
                  }
                }

                cat("\\\\cellcolor{", cellColor, "} ", sep = "")

                if (j < length(requirementStats)) {
                  cat(" & ")
                } else {
                  cat(" \\\\\\\\\\n")
                }
              }
            }

            cat("\\\\hline\\n")
            cat("\\\\end{tabular}%\\n")
            cat("}\\n")
            cat("\\\\end{table}\\n\\n")
          }
        }

        cat("\\n\\\\pagebreak\\n")
      }
    }
  }
} else {
  cat("No analysis data available.\\n")
}


```

---

**Report Generated:** `r format(Sys.time(), "%B %d, %Y at %H:%M:%S")`
'

writeLines(rmdContent, tempRmd)

tryCatch({
	rmarkdown::render(
		tempRmd,
		output_format = "pdf_document",
		output_file = file,
		params = list(results = results),
		quiet = TRUE
	)
	message("PDF report generated successfully: ", file)
}, error = function(e) {
	stop("PDF generation failed: ", e$message)
})

unlink(tempRmd)
}

#Test data

dbNames <- c("Test_1", "Test_2", "Test_3",
              "SomeDB_SomeDate", "Test_4", "SomeNameIComeUpWithHave_youngPadawan",
              "2b||!2b", "Test_5", "That'sTheLimitOfMyImagination")


allStats <- c(
  "propWithCalendarTime", "propInAgeRange", "propWithAgeAtFirstObs",
  "propWithEthnicityCriteria", "propWithGenderCriteria",
  "propWithLongitudinalCriteria", "propWithRaceCriteria",
  "propWithRequiredComparatorConcepts", "propWithRequiredDomain",
  "propWithRequiredOutcomeConcepts", "propWithRequiredTargetConcepts",
  "propWithRequiredIndicationConcepts", "minSampleSize",
  "propWithERCriteria", "propMeasRecordsWithValues", "propWithProcedureCriteria",
  "propWithObservationCriteria", "propWithDeathCriteria", "propWithOPCriteria",
  "propWithMeasurementCriteria", "propWithIPCriteria", "propWithDrugCriteria",
  "propWithDeviceCriteria", "propWithConditionCriteria"
)

specValues <- c(
  "192903-202412", "aged 0-150", "age 0-150", "38003563", "8507", "365 days",
  "8515", "hydrochlorothiazide", "condition,drug", "myocardial_infarction",
  "lisinopril", "hypertension", ">1000",
  "myocardial_infarction", "myocardial_infarction", "myocardial_infarction",
  "myocardial_infarction", "myocardial_infarction", "myocardial_infarction",
  "myocardial_infarction", "myocardial_infarction", "myocardial_infarction",
  "myocardial_infarction", "myocardial_infarction"
)

nStats <- length(allStats)
nRows <- 3 * 9 * nStats

results <- data.frame(
  analysisId = rep(1:3, each = nStats * 9),
  analysisName = rep(c("Hypertension_Study", "Diabetes_Analysis", "ScaryAffliction_study"), each = nStats * 9),
  databaseId = rep(rep(dbNames, each = nStats), 3),
  statistic = rep(allStats, 27),
  value = sample(100:50000, nRows, replace = TRUE),
  proportion = runif(nRows, 0.01, 1),
  spec = rep(specValues, 27),
  evaluateThreshold = rep(c(1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, rep(1, 11)), 27),
  threshold = rep(c(0.05, 0.05, 0.01, 0.05, 0.05, 0.05, 0.05, 0, 0.05, 0, 0, 0, 0, rep(0.05, 11)), 27),
  status = sample(c("pass", "pass", "pass", "fail", NA), nRows, replace = TRUE, prob = c(0.7, 0.1, 0.1, 0.1, 0.3)),
  fail = sample(0:1, nRows, replace = TRUE, prob = c(0.75, 0.25)),
  stringsAsFactors = FALSE
)


#Test

# createPdfReport(results = results,
#                 file = "~/Desktop/db_diagnostics_results_test.pdf")
