# @file GeneratePDF.R
#
# Copyright 2025 Observational Health Data Sciences and Informatics
#
# This file is part of the DbDiagnostics package
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' createPdfReport

#' @param results DbDiagnostics results table
#' @param file Name and location for generated report, example: "./report.pdf"

#' @export

createPdfReport <- function(results, file,
                            reportName = "User Defined Report Name",
														userNotes = NULL,
                            analysisSettings = NULL
) {
  tempRmd <- tempfile(fileext = ".Rmd")
  rmdContent <- '
---
title: ""
author: ""
date: ""
output:
  pdf_document:
    latex_engine: xelatex
    toc: false
header-includes:
  - \\usepackage{colortbl}
  - \\usepackage{xcolor}
  - \\definecolor{pass}{RGB}{76,175,80}
  - \\definecolor{fail}{RGB}{244,67,54}
  - \\definecolor{na}{RGB}{204,204,204}
  - \\definecolor{infoback}{RGB}{227,242,253}
  - \\definecolor{infoborder}{RGB}{66,133,244}
  - \\definecolor{notesback}{RGB}{224,242,241}
  - \\definecolor{notesborder}{RGB}{77,142,142}
  - \\definecolor{rowgray}{RGB}{245,245,245}
  - \\definecolor{tablerule}{RGB}{150,150,150}
  - \\definecolor{headerblue}{RGB}{220,230,242}
  - \\setlength{\\arrayrulewidth}{1pt}
  - \\arrayrulecolor{tablerule}
  - \\renewcommand{\\arraystretch}{1.2}
  - \\usepackage{float}
  - \\usepackage{tcolorbox}
  - \\usepackage{booktabs}
  - \\usepackage{fontawesome5}
  - \\newtcolorbox{accentbox}{colback=rowgray, colframe=tablerule, boxrule=1pt, arc=3pt, left=10pt, right=10pt, top=8pt, bottom=8pt, boxsep=0pt}
  - \\newtcolorbox{infobox}{colback=infoback, colframe=infoborder, boxrule=1pt, arc=3pt, left=6pt, right=6pt, top=6pt, bottom=6pt, boxsep=0pt}
  - \\newtcolorbox{notesbox}{colback=notesback, colframe=notesborder, boxrule=1pt, arc=3pt, left=6pt, right=6pt, top=6pt, bottom=6pt, boxsep=0pt}

params:
  results: !r NULL
  reportName: "Database Diagnostics Report"
  userNotes: !r NULL
  analysisSettings: !r NULL
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(knitr)

results <- params$results
reportName <- params$reportName
userNotes <- params$userNotes
analysisSettings <- params$analysisSettings


if (!is.null(results)) {
  if ("proportion" %in% names(results)) {
    results$proportion <- as.numeric(as.character(results$proportion))
  }
  if ("value" %in% names(results)) {
    results$value <- as.numeric(as.character(results$value))
  }
}
```

\\thispagestyle{empty}
\\vspace*{\\fill}
\\begin{center}
\\Huge\\textbf{`r reportName`}

\\vspace{2cm}

\\Large Generated by DbDiagnostics

\\vspace{1cm}

\\large `r format(Sys.Date(), "%B %d, %Y")`
\\end{center}
\\vspace*{\\fill}

\\pagebreak


```{r analysis-details, results="asis"}
if (!is.null(results) && is.data.frame(results) && nrow(results) > 0 && "analysisName" %in% names(results)) {

  uniqueAnalyses <- unique(results$analysisName[!is.na(results$analysisName)])

  # T/C/I/O SECTION


  for (i in seq_along(uniqueAnalyses)) {
    analysisName <- uniqueAnalyses[i]

    analysisEscaped <- gsub("_", "\\\\\\\\_", as.character(analysisName))

    cat("\\\\begin{center}\\n")
    cat("\\\\Large\\\\textbf{Analysis ", i, ": ", analysisEscaped, "}\\n", sep = "")
    cat("\\\\end{center}\\n\\n")

		cat("\\\\subsection*{Overview:}\\n\\n")

    analysisData <- results[!is.na(results$analysisName) & results$analysisName == analysisName, ]

    if ("databaseId" %in% names(analysisData)) {
      uniqueDbsAnalysis <- unique(analysisData$databaseId[!is.na(analysisData$databaseId)])

      if (length(uniqueDbsAnalysis) > 0) {
        conceptTypes <- list(
          Target = "propWithRequiredTargetConcepts",
          Comparator = "propWithRequiredComparatorConcepts",
          Indication = "propWithRequiredIndicationConcepts",
          Outcome = "propWithRequiredOutcomeConcepts"
        )

       cat("\\\\begin{table}[H]\\n")
			 cat("\\\\centering\\n")
			 cat("\\\\begin{tabular}{|l|c|c|c|c|}\\n")
			 cat("\\\\hline\\n")
			 cat("\\\\textbf{Database} & \\\\textbf{T} & \\\\textbf{C} & \\\\textbf{I} & \\\\textbf{O} \\\\\\\\\\n")
			 cat("\\\\hline\\n")

        passCount <- 0
        failCount <- 0
        naCount <- 0
        rowCount <- 0

        for (db in uniqueDbsAnalysis) {
          dbResults <- analysisData[!is.na(analysisData$databaseId) & analysisData$databaseId == db, ]

          dbEscaped <- gsub("_", "\\\\\\\\_", db)

          cat(dbEscaped, " & ")


          for (i in seq_along(conceptTypes)) {
            statisticName <- conceptTypes[[i]]

            cellColor <- "na"
            statRow <- data.frame()

            if ("statistic" %in% names(dbResults)) {
              statRow <- dbResults[!is.na(dbResults$statistic) &
                                      dbResults$statistic == statisticName, ]

              if (nrow(statRow) > 0 && "status" %in% names(statRow)) {
                statusVal <- statRow$status[1]
                if (!is.na(statusVal)) {
                  if (tolower(statusVal) == "pass") {
                    cellColor <- "pass"
                    passCount <- passCount + 1
                  } else if (tolower(statusVal) == "fail") {
                    cellColor <- "fail"
                    failCount <- failCount + 1
                  } else {
                    naCount <- naCount + 1
                  }
                } else {
                  naCount <- naCount + 1
                }
              } else {
                naCount <- naCount + 1
              }
            } else {
              naCount <- naCount + 1
            }

            propVal <- "N/A"
            if (nrow(statRow) > 0 && "proportion" %in% names(statRow) && !is.na(statRow$proportion[1])) {
              propVal <- paste0(round(statRow$proportion[1] * 100, 2), "\\\\%")
            }

            cat("\\\\cellcolor{", cellColor, "} ", propVal, sep = "")

            if (i < length(conceptTypes)) {
              cat(" & ")
            } else {
              cat(" \\\\\\\\\\n\\\\hline\\n")
            }
          }
        }

        cat("\\\\end{tabular}\\n")
        cat("\\\\end{table}\\n\\n")
        cat("\\\\vspace{0.3cm}\\n")



        totalChecks <- length(uniqueDbsAnalysis) * length(conceptTypes)

       dbMeetAll <- 0
			 for (db in uniqueDbsAnalysis) {
	     dbResults <- analysisData[!is.na(analysisData$databaseId) & analysisData$databaseId == db, ]
	     meetsAll <- TRUE
			 for (statName in c("propWithRequiredTargetConcepts", "propWithRequiredComparatorConcepts",
													"propWithRequiredIndicationConcepts", "propWithRequiredOutcomeConcepts")) {
				statRow <- dbResults[!is.na(dbResults$statistic) & dbResults$statistic == statName, ]
				if (nrow(statRow) > 0 && "status" %in% names(statRow)) {
					statusVal <- statRow$status[1]
					if (is.na(statusVal)) {
						next
					}
					if (tolower(statusVal) != "pass") {
						meetsAll <- FALSE
						break
					}
				}
			}
			if (meetsAll) {
				dbMeetAll <- dbMeetAll + 1
			}
		}
				percentMeetAll <- ifelse(length(uniqueDbsAnalysis) > 0,
													 round((dbMeetAll / length(uniqueDbsAnalysis)) * 100, 2),
													 0)

		cat("\\\\begin{accentbox}\\n")
		cat("\\\\textbf{Percent of databases that meet all T/C/I/O:} ", percentMeetAll, "\\\\%\\n", sep = "")
		cat("\\\\end{accentbox}\\n\\n")
		cat("\\\\vspace{0.1cm}\\n")

		cat("\\\\begin{infobox}\\n")
        cat("\\\\faInfoCircle\\\\hspace{0.3cm}\\\\textbf{About T/C/I/O Metrics}\\n\\n")
        cat("This table shows a high-level overview of available databases and Target (T), Comparator (C), Incidence (I) and Outcome (O) requirements for the study. The percentage indicates the number of persons in the database that have at least one of the concepts defined for the T/C/I/O and the color indicates if a database has all study requirements as defined by the user. \\\\newline\\n")
        cat("Green = all elements of the study are available, red = one or more elements of the study are not available, grey - data is not available. \\n")
        cat("\\\\end{infobox}\\n\\n")


        # COMPARATOR SECTION

         cat("\\\\pagebreak\\n")
        cat("\\\\begin{center}\\n")
        cat("\\\\Large\\\\textbf{Target and Comparators}\\n")
        cat("\\\\end{center}\\n\\n")

        comparatorData <- analysisData[!is.na(analysisData$statistic) &
                                        analysisData$statistic == "propWithRequiredComparatorConcepts", ]

        if (nrow(comparatorData) > 0 && "spec" %in% names(comparatorData)) {
          compNames <- unique(comparatorData$spec[!is.na(comparatorData$spec)])

          if (length(compNames) > 0) {
            compName <- compNames[1]
            compEscaped <- gsub("_", "\\\\\\\\_", as.character(compName))

            cat("\\\\begin{minipage}{\\\\textwidth}\\n")
            cat("\\\\vspace{0.5cm}\\n")
            cat("\\\\noindent\\\\textbf{Comparator: ", compEscaped, "}\\n\\n", sep = "")

            compSubset <- comparatorData[!is.na(comparatorData$spec) & comparatorData$spec == compName, ]

            if (nrow(compSubset) > 0 && "databaseId" %in% names(compSubset)) {
              compSubset <- compSubset[order(compSubset$databaseId), ]

              cat("\\\\begin{table}[H]\\n")
              cat("\\\\centering\\n")
              cat("\\\\begin{tabular}{|l|r|r|}\\n")
              cat("\\\\hline\\n")
              cat("\\\\textbf{Database} & \\\\textbf{Count} & \\\\textbf{Proportion} \\\\\\\\\\n")
              cat("\\\\hline\\n")

              rowNum <- 0
              for (i in 1:nrow(compSubset)) {
                rowNum <- rowNum + 1

                row <- compSubset[i, ]

                dbName <- ifelse(is.na(row$databaseId), "Unknown", as.character(row$databaseId))
                dbEscaped <- gsub("_", "\\\\\\\\_", dbName)

                countVal <- ifelse("value" %in% names(row) && !is.na(row$value),
                                  format(round(row$value), big.mark = ","),
                                  "N/A")

                if ("proportion" %in% names(row) && !is.na(row$proportion)) {
                  propVal <- paste0(round(row$proportion * 100, 2), "\\\\%")
                } else {
                  propVal <- "N/A"
                }

                 if (rowNum %% 2 == 0) {
                  cat("\\\\rowcolor{rowgray} ")
                }

                cat(dbEscaped, " & ", countVal, " & ", propVal, " \\\\\\\\\\n", sep = "")
              }

              cat("\\\\hline\\n")
              cat("\\\\end{tabular}\\n")
              cat("\\\\end{table}\\n\\n")

              cat("\\\\begin{infobox}\\n")
			  cat("\\\\faInfoCircle\\\\hspace{0.3cm}\\\\textbf{About Comparator Table}\\n\\n")
			  cat("The count and percent of persons in the database with a record of at least one concept defined for the comparator \\n")
			  cat("\\\\end{infobox}\\n\\n")

              cat("\\\\end{minipage}\\n\\n")
            }
          }
        }



        # TARGET SECTION
        targetData <- analysisData[!is.na(analysisData$statistic) &
                                     analysisData$statistic == "propWithRequiredTargetConcepts", ]

        if (nrow(targetData) > 0 && "spec" %in% names(targetData)) {
          targetNames <- unique(targetData$spec[!is.na(targetData$spec)])

          if (length(targetNames) > 0) {
            for (targetName in targetNames) {
              targetEscaped <- gsub("_", "\\\\\\\\_", as.character(targetName))

              cat("\\\\begin{minipage}{\\\\textwidth}\\n")
              cat("\\\\vspace{0.5cm}\\n")
              cat("\\\\noindent\\\\textbf{Target: ", targetEscaped, "}\\n\\n", sep = "")

              targetSubset <- targetData[!is.na(targetData$spec) & targetData$spec == targetName, ]

              if (nrow(targetSubset) > 0 && "databaseId" %in% names(targetSubset)) {

                targetSubset <- targetSubset[order(targetSubset$databaseId), ]

                cat("\\\\begin{table}[H]\\n")
                cat("\\\\centering\\n")
                cat("\\\\begin{tabular}{|l|r|r|}\\n")
                cat("\\\\hline\\n")
                cat("\\\\textbf{Database} & \\\\textbf{Count} & \\\\textbf{Proportion} \\\\\\\\\\n")
                cat("\\\\hline\\n")

                rowNum <- 0
                for (i in 1:nrow(targetSubset)) {
                  rowNum <- rowNum + 1
                  row <- targetSubset[i, ]

                  dbName <- ifelse(is.na(row$databaseId), "Unknown", as.character(row$databaseId))
                  dbEscaped <- gsub("_", "\\\\\\\\_", dbName)

                  countVal <- ifelse("value" %in% names(row) && !is.na(row$value),
                                    format(round(row$value), big.mark = ","),
                                    "N/A")

                  if ("proportion" %in% names(row) && !is.na(row$proportion)) {
                    propVal <- paste0(round(row$proportion * 100, 2), "\\\\%")
                  } else {
                    propVal <- "N/A"
                  }

                   if (rowNum %% 2 == 0) {
                    cat("\\\\rowcolor{rowgray} ")
                  }

                  cat(dbEscaped, " & ", countVal, " & ", propVal, " \\\\\\\\\\n", sep = "")
                }

                cat("\\\\hline\\n")
                cat("\\\\end{tabular}\\n")
                cat("\\\\end{table}\\n\\n")


	            cat("\\\\begin{infobox}\\n")
				cat("\\\\faInfoCircle\\\\hspace{0.3cm}\\\\textbf{About Target Table}\\n\\n")
				cat("The count and percent of persons in the database with a record of at least one concept defined for the target \\n")
				cat("\\\\end{infobox}\\n\\n")

                cat("\\\\end{minipage}\\n\\n")
              }
            }
          }
        }

         # TARGET/COMPARATOR REQUIREMENTS SECTION
        cat("\\\\begin{minipage}{\\\\textwidth}\\n")
        cat("\\\\vspace{0.5cm}\\n")
        cat("\\\\noindent\\\\textbf{Target/Comparator Requirements}\\n\\n")

        if ("databaseId" %in% names(analysisData)) {
          uniqueDbsAnalysis <- unique(analysisData$databaseId[!is.na(analysisData$databaseId)])

          if (length(uniqueDbsAnalysis) > 0) {
            requirementStats <- c(
              "propWithCalendarTime",
              "propInAgeRange",
              "propWithAgeAtFirstObs",
              "propWithLongitudinalCriteria",
              "propWithRaceCriteria",
              "propWithRequiredDomain"
            )

            cat("\\\\begin{table}[H]\\n")
            cat("\\\\centering\\n")
            cat("\\\\resizebox{\\\\textwidth}{!}{%\\n")
            cat("\\\\begin{tabular}{|l|c|c|c|c|c|c|}\\n")
            cat("\\\\hline\\n")
            cat("\\\\textbf{Database} & \\\\textbf{Calendar Time} & \\\\textbf{Age Range} & \\\\textbf{Age at First Obs} & \\\\textbf{Longitudinal} & \\\\textbf{Race} & \\\\textbf{Domain} \\\\\\\\\\n")
            cat("\\\\hline\\n")

            for (db in uniqueDbsAnalysis) {
              dbAnalysisResults <- analysisData[!is.na(analysisData$databaseId) &
                                                  analysisData$databaseId == db, ]

              dbEscaped <- gsub("_", "\\\\\\\\_", db)
              cat(dbEscaped, " & ")

              for (j in seq_along(requirementStats)) {
                statName <- requirementStats[j]

                cellColor <- "na"

                if ("statistic" %in% names(dbAnalysisResults)) {
                  statRow <- dbAnalysisResults[!is.na(dbAnalysisResults$statistic) &
                                                 dbAnalysisResults$statistic == statName, ]

                  if (nrow(statRow) > 0 && "status" %in% names(statRow)) {
                    statusVal <- statRow$status[1]
                    if (!is.na(statusVal)) {
                      if (tolower(statusVal) == "pass") {
                        cellColor <- "pass"
                      } else if (tolower(statusVal) == "fail") {
                        cellColor <- "fail"
                      }
                    }
                  }
                }

                cat("\\\\cellcolor{", cellColor, "} ", sep = "")

                if (j < length(requirementStats)) {
                  cat(" & ")
                } else {
                                cat(" \\\\\\\\\\n\\\\hline\\n")

                }
              }
            }

            cat("\\\\end{tabular}%\\n")
            cat("}\\n")
            cat("\\\\end{table}\\n\\n")

            cat("\\\\begin{infobox}\\n")
		 	cat("\\\\faInfoCircle\\\\hspace{0.3cm}\\\\textbf{About Target/Comparator Requirements Table}\\n\\n")
			cat("The count and percent of persons in the database with a record of at least one concept defined for the comparator \\n")
			cat("\\\\end{infobox}\\n\\n")

            cat("\\\\end{minipage}\\n\\n")
          }
        }

        # OUTCOME SECTION
        outcomeData <- analysisData[!is.na(analysisData$statistic) &
                                     analysisData$statistic == "propWithRequiredOutcomeConcepts", ]

        if (nrow(outcomeData) > 0 && "spec" %in% names(outcomeData)) {
          outcomeNames <- unique(outcomeData$spec[!is.na(outcomeData$spec)])

          if (length(outcomeNames) > 0) {
            for (outcomeName in outcomeNames) {
              outcomeEscaped <- gsub("_", "\\\\\\\\_", as.character(outcomeName))

              cat("\\\\begin{minipage}{\\\\textwidth}\\n")
              cat("\\\\vspace{0.5cm}\\n")
              cat("\\\\noindent\\\\textbf{Outcome: ", outcomeEscaped, "}\\n\\n", sep = "")

              outcomeAllStats <- analysisData[!is.na(analysisData$spec) &
                                                analysisData$spec == outcomeName, ]

              if ("databaseId" %in% names(outcomeAllStats)) {
                uniqueDbsOutcome <- unique(outcomeAllStats$databaseId[!is.na(outcomeAllStats$databaseId)])

                if (length(uniqueDbsOutcome) > 0) {
                  allOutcomeStats <- list(
                    list(stat = "propWithRequiredOutcomeConcepts", label = "Concepts"),
                    list(stat = "propWithERCriteria", label = "ER"),
                    list(stat = "propMeasRecordsWithValues", label = "Meas"),
                    list(stat = "propWithProcedureCriteria", label = "Proc"),
                    list(stat = "propWithObservationCriteria", label = "Obs"),
                    list(stat = "propWithDeathCriteria", label = "Death"),
                    list(stat = "propWithOPCriteria", label = "OP"),
                    list(stat = "propWithMeasurementCriteria", label = "Meas"),
                    list(stat = "propWithIPCriteria", label = "IP"),
                    list(stat = "propWithGenderCriteria", label = "Gender"),
                    list(stat = "propWithEthnicityCriteria", label = "Ethnic"),
                    list(stat = "propWithDrugCriteria", label = "Drug"),
                    list(stat = "propWithDeviceCriteria", label = "Device"),
                    list(stat = "propWithConditionCriteria", label = "Cond")
                  )

                  # Filter to only columns with data
                  columnsWithData <- list()
                  for (col in allOutcomeStats) {
                    statRows <- outcomeAllStats[!is.na(outcomeAllStats$statistic) &
                                                 outcomeAllStats$statistic == col$stat, ]
                    if (nrow(statRows) > 0) {
                      hasData <- FALSE
                      for (k in 1:nrow(statRows)) {
                        if (("status" %in% names(statRows) && !is.na(statRows$status[k])) ||
                            ("proportion" %in% names(statRows) && !is.na(statRows$proportion[k]))) {
                          hasData <- TRUE
                          break
                        }
                      }
                      if (hasData) {
                        columnsWithData <- c(columnsWithData, list(col))
                      }
                    }
                  }

                  if (length(columnsWithData) > 0) {
                    # Split into chunks of max 6 columns per table
                    maxCols <- 6
                    chunks <- split(columnsWithData, ceiling(seq_along(columnsWithData) / maxCols))

                    for (chunkIndex in seq_along(chunks)) {
                      chunk <- chunks[[chunkIndex]]
                      numCols <- length(chunk)

                      colSpec <- paste0("|l|", paste(rep("c|", numCols), collapse = ""))

                      cat("\\\\begin{table}[H]\\n")
                      cat("\\\\centering\\n")
                      cat("\\\\begin{tabular}{", colSpec, "}\\n", sep = "")
                      cat("\\\\hline\\n")

                      headerParts <- c("\\\\textbf{Database}")
                      for (col in chunk) {
                        headerParts <- c(headerParts, paste0("\\\\textbf{", col$label, "}"))
                      }
                      cat(paste(headerParts, collapse = " & "), " \\\\\\\\\\n", sep = "")
                      cat("\\\\hline\\n")

                      for (db in uniqueDbsOutcome) {
                        dbResults <- outcomeAllStats[!is.na(outcomeAllStats$databaseId) &
                                                       outcomeAllStats$databaseId == db, ]
                        dbEscaped <- gsub("_", "\\\\\\\\_", db)
                        cat(dbEscaped, " & ")

                        for (j in seq_along(chunk)) {
                          col <- chunk[[j]]
                          cellColor <- "na"
                          cellText <- ""

                          statRow <- dbResults[!is.na(dbResults$statistic) &
                                                dbResults$statistic == col$stat, ]

                          if (nrow(statRow) > 0) {
                            if ("status" %in% names(statRow) && !is.na(statRow$status[1])) {
                              statusVal <- statRow$status[1]
                              if (tolower(statusVal) == "pass") {
                                cellColor <- "pass"
                              } else if (tolower(statusVal) == "fail") {
                                cellColor <- "fail"
                              }
                              if ("proportion" %in% names(statRow) && !is.na(statRow$proportion[1])) {
                                cellText <- paste0(round(statRow$proportion[1] * 100, 2), "\\\\%")
                              }
                            } else if ("fail" %in% names(statRow) && !is.na(statRow$fail[1])) {
                              failVal <- statRow$fail[1]
                              if (failVal == 0) {
                                cellColor <- "pass"
                              } else if (failVal == 1) {
                                cellColor <- "fail"
                              }
                            }
                          }

                          cat("\\\\cellcolor{", cellColor, "} ", cellText, sep = "")

                          if (j < length(chunk)) {
                            cat(" & ")
                          } else {
                            cat(" \\\\\\\\\\n\\\\hline\\n")
                          }
                        }
                      }

                      cat("\\\\end{tabular}\\n")
                      cat("\\\\end{table}\\n")

                      if (chunkIndex < length(chunks)) {
                        cat("\\\\vspace{0.2cm}\\n")
                      }
                    }
                  }
                }
              }

              cat("\\\\begin{infobox}\\n")
			  cat("\\\\faInfoCircle\\\\hspace{0.3cm}\\\\textbf{About Outcome Table}\\n\\n")
			  cat("This table shows which databases have the specified requirements for the outcome. A database is indicated as green when > 0% of the patients in the database have a record in each individual domain. \\n")
			  cat("\\\\end{infobox}\\n\\n")
              cat("\\\\end{minipage}\\n\\n")
            }
          }
        }

      # ANALYSIS SPECIFICATIONS SECTION
        if (!is.null(analysisSettings)) {
          currentSettings <- NULL
          for (s in analysisSettings) {
            if (!is.null(s$analysisId) && !is.null(analysisData$analysisId) &&
                s$analysisId == unique(analysisData$analysisId)[1]) {
              currentSettings <- s
              break
            }
          }

          if (is.null(currentSettings)) {
            for (s in analysisSettings) {
              if (!is.null(s$analysisName) && s$analysisName == analysisName) {
                currentSettings <- s
                break
              }
            }
          }

          if (!is.null(currentSettings)) {
            cat("\\\\pagebreak\\n")
            cat("\\\\begin{center}\\n")
            cat("\\\\large\\\\textbf{Analysis Specifications}\\n")
            cat("\\\\end{center}\\n\\n")

            cat("\\\\begin{infobox}\\n")
            cat("\\\\faInfoCircle\\\\hspace{0.3cm}The following parameters were used to configure this analysis.\\n")
            cat("\\\\end{infobox}\\n\\n")

            specGroups <- list(
              list(
                title = "Population Criteria",
                fields = list(
                  list(name = "minAge", label = "Minimum Age"),
                  list(name = "maxAge", label = "Maximum Age"),
                  list(name = "studyStartDate", label = "Study Start Date"),
                  list(name = "studyEndDate", label = "Study End Date"),
                  list(name = "requiredDurationDays", label = "Required Duration (Days)")
                )
              ),
              list(
                title = "Domain Requirements",
                fields = list(
                  list(name = "requiredDomains", label = "Required Domains"),
                  list(name = "desiredDomains", label = "Desired Domains"),
                  list(name = "requiredVisits", label = "Required Visits"),
                  list(name = "desiredVisits", label = "Desired Visits")
                )
              ),
              list(
                title = "Cohort Definitions",
                fields = list(
                  list(name = "targetName", label = "Target"),
                  list(name = "comparatorName", label = "Comparator"),
                  list(name = "indicationName", label = "Indication"),
                  list(name = "outcomeName", label = "Outcome")
                )
              ),
              list(
                title = "Additional Settings",
                fields = list(
                  list(name = "targetUseDrugEra", label = "Target Use Drug Era"),
                  list(name = "comparatorUseDrugEra", label = "Comparator Use Drug Era")
                )
              )
            )

            for (group in specGroups) {
              hasData <- FALSE
              for (field in group$fields) {
                val <- currentSettings[[field$name]]
                if (!is.null(val) && length(val) > 0 && !all(is.na(val))) {
                  hasData <- TRUE
                  break
                }
              }

              if (hasData) {
                cat("\\\\vspace{0.3cm}\\n")
                cat("\\\\noindent\\\\textbf{", group$title, "}\\n\\n", sep = "")

                cat("\\\\begin{table}[H]\\n")
                cat("\\\\centering\\n")
                cat("\\\\begin{tabular}{@{} p{5cm} p{9cm} @{}}\\n")
                cat("\\\\toprule\\n")

                rowNum <- 0
                for (field in group$fields) {
                  val <- currentSettings[[field$name]]
                  if (!is.null(val) && length(val) > 0 && !all(is.na(val))) {
                    rowNum <- rowNum + 1

                    if (is.logical(val)) {
                      displayVal <- ifelse(val, "Yes", "No")
                    } else if (is.vector(val) && length(val) > 1) {
                      displayVal <- paste(val, collapse = ", ")
                    } else {
                      displayVal <- as.character(val)
                    }

                    displayVal <- gsub("_", "\\\\\\\\_", displayVal)
                    labelEscaped <- gsub("_", "\\\\\\\\_", field$label)

                    if (rowNum %% 2 == 0) {
                      cat("\\\\rowcolor{rowgray} ")
                    }
                    cat(labelEscaped, " & ", displayVal, " \\\\\\\\\\n", sep = "")
                  }
                }

                cat("\\\\bottomrule\\n")
                cat("\\\\end{tabular}\\n")
                cat("\\\\end{table}\\n\\n")
              }
            }
          }
        }


       # USER NOTES
        if (!is.null(userNotes) && length(userNotes) > 0) {
          currentAnalysisId <- unique(analysisData$analysisId)[1]

          matchingNotes <- list()
          for (note in userNotes) {
            noteMatches <- FALSE

            if (!is.null(note$analysisId) && !is.null(currentAnalysisId)) {
              if (note$analysisId == currentAnalysisId) {
                noteMatches <- TRUE
              }
            } else if (!is.null(note$analysisName) && note$analysisName == analysisName) {
              noteMatches <- TRUE
            }

            if (noteMatches && !is.null(note$text) && nchar(trimws(note$text)) > 0) {
              matchingNotes <- c(matchingNotes, list(note))
            }
          }

          if (length(matchingNotes) > 0) {
            cat("\\\\pagebreak\\n")
            cat("\\\\begin{center}\\n")
            cat("\\\\large\\\\textbf{User Notes}\\n")
            cat("\\\\end{center}\\n\\n")

            for (noteIndex in seq_along(matchingNotes)) {
              note <- matchingNotes[[noteIndex]]

              cat("\\\\begin{notesbox}\\n")
              cat("\\\\faPencil*\\\\hspace{0.3cm}", note$text, "\\n", sep = "")
              cat("\\\\end{notesbox}\\n")

              if (noteIndex < length(matchingNotes)) {
                cat("\\\\vspace{0.3cm}\\n")
              }
            }
            cat("\\n")
          }
        }

        cat("\\n\\\\pagebreak\\n")
      }
    }
  }
} else {
  cat("No analysis data available.\\n")
}


```

```{r concept-ids, results="asis"}
if (!is.null(analysisSettings)) {
  hasAnyConcepts <- FALSE
  for (s in analysisSettings) {
    conceptFields <- c("targetConceptIds", "comparatorConceptIds", "indicationConceptIds", "outcomeConceptIds", "genderConceptIds", "raceConceptIds", "ethnicityConceptIds")
    for (field in conceptFields) {
      if (!is.null(s[[field]]) && length(s[[field]]) > 0) {
        hasAnyConcepts <- TRUE
        break
      }
    }
    if (hasAnyConcepts) break
  }

  if (hasAnyConcepts) {
    cat("\\\\pagebreak\\n")
    cat("\\\\begin{center}\\n")
    cat("\\\\Large\\\\textbf{Concept IDs Reference}\\n")
    cat("\\\\end{center}\\n\\n")

    cat("\\\\begin{infobox}\\n")
    cat("\\\\faInfoCircle\\\\hspace{0.3cm}The following OMOP concept IDs were used to define cohorts and criteria in this analysis.\\n")
    cat("\\\\end{infobox}\\n\\n")

    conceptFieldLabels <- list(
      targetConceptIds = "Target Concepts",
      comparatorConceptIds = "Comparator Concepts",
      indicationConceptIds = "Indication Concepts",
      outcomeConceptIds = "Outcome Concepts",
      genderConceptIds = "Gender Concepts",
      raceConceptIds = "Race Concepts",
      ethnicityConceptIds = "Ethnicity Concepts"
    )

    for (s in analysisSettings) {
      analysisLabel <- if (!is.null(s$analysisName)) s$analysisName else paste("Analysis", s$analysisId)
      analysisLabel <- gsub("_", "\\\\\\\\_", analysisLabel)

      hasConceptsThisAnalysis <- FALSE
      for (field in names(conceptFieldLabels)) {
        if (!is.null(s[[field]]) && length(s[[field]]) > 0) {
          hasConceptsThisAnalysis <- TRUE
          break
        }
      }

      if (hasConceptsThisAnalysis) {
        cat("\\\\subsection*{", analysisLabel, "}\\n\\n", sep = "")

        for (field in names(conceptFieldLabels)) {
          ids <- s[[field]]
          if (!is.null(ids) && length(ids) > 0) {
            label <- conceptFieldLabels[[field]]

            cat("\\\\vspace{0.3cm}\\n")
            cat("\\\\noindent\\\\textbf{", label, "} \\\\hfill \\\\textit{", length(ids), " concept(s)}\\n\\n", sep = "")

            cat("\\\\begin{tcolorbox}[colback=rowgray, colframe=rowgray, boxrule=0pt, arc=2pt, left=8pt, right=8pt, top=6pt, bottom=6pt]\\n")
            cat("\\\\ttfamily\\\\small ", paste(ids, collapse = ", "), "\\n", sep = "")
            cat("\\\\end{tcolorbox}\\n\\n")
          }
        }
      }
    }
  }
}
```

---

**Report Generated:** `r format(Sys.time(), "%B %d, %Y at %H:%M:%S")`
'

  writeLines(rmdContent, tempRmd)

  tryCatch({
    rmarkdown::render(
      tempRmd,
      output_format = "pdf_document",
      output_file = file,
      params = list(results = results, reportName = reportName, userNotes = userNotes, analysisSettings = analysisSettings),
      quiet = TRUE
    )
    message("PDF report generated successfully: ", file)
  }, error = function(e) {
    stop("PDF generation failed: ", e$message)
  })

  unlink(tempRmd)
}

#Test data

dbNames <- c("Test_1", "Test_2", "Test_3",
             "SomeDB_SomeDate", "Test_4", "SomeNameIComeUpWithHave_youngPadawan",
             "2b||!2b", "Test_5", "That'sTheLimitOfMyImagination")


allStats <- c(
  "propWithCalendarTime", "propInAgeRange", "propWithAgeAtFirstObs",
  "propWithEthnicityCriteria", "propWithGenderCriteria",
  "propWithLongitudinalCriteria", "propWithRaceCriteria",
  "propWithRequiredComparatorConcepts", "propWithRequiredDomain",
  "propWithRequiredOutcomeConcepts", "propWithRequiredTargetConcepts",
  "propWithRequiredIndicationConcepts", "minSampleSize",
  "propWithERCriteria", "propMeasRecordsWithValues", "propWithProcedureCriteria",
  "propWithObservationCriteria", "propWithDeathCriteria", "propWithOPCriteria",
  "propWithMeasurementCriteria", "propWithIPCriteria", "propWithDrugCriteria",
  "propWithDeviceCriteria", "propWithConditionCriteria"
)

specValues <- c(
  "192903-202412", "aged 0-150", "age 0-150", "38003563", "8507", "365 days",
  "8515", "hydrochlorothiazide", "condition,drug", "myocardial_infarction",
  "lisinopril", "hypertension", ">1000",
  "myocardial_infarction", "myocardial_infarction", "myocardial_infarction",
  "myocardial_infarction", "myocardial_infarction", "myocardial_infarction",
  "myocardial_infarction", "myocardial_infarction", "myocardial_infarction",
  "myocardial_infarction", "myocardial_infarction"
)

nStats <- length(allStats)
nRows <- 3 * 9 * nStats

results <- data.frame(
  analysisId = rep(1:3, each = nStats * 9),
  analysisName = rep(c("Hypertension_Study", "Diabetes_Analysis", "ScaryAffliction_study"), each = nStats * 9),
  databaseId = rep(rep(dbNames, each = nStats), 3),
  statistic = rep(allStats, 27),
  value = sample(100:50000, nRows, replace = TRUE),
  proportion = runif(nRows, 0.01, 1),
  spec = rep(specValues, 27),
  evaluateThreshold = rep(c(1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, rep(1, 11)), 27),
  threshold = rep(c(0.05, 0.05, 0.01, 0.05, 0.05, 0.05, 0.05, 0, 0.05, 0, 0, 0, 0, rep(0.05, 11)), 27),
  status = sample(c("pass", "pass", "pass", "fail", NA), nRows, replace = TRUE, prob = c(0.7, 0.1, 0.1, 0.1, 0.3)),
  fail = sample(0:1, nRows, replace = TRUE, prob = c(0.75, 0.25)),
  stringsAsFactors = FALSE
)

analysisSettings <- list(
  list(
    analysisId = 1,
    analysisName = "Hypertension_Study",
    minAge = 18,
    maxAge = 85,
    genderConceptIds = c(8507, 8532),
    raceConceptIds = c(8515, 8516),
    ethnicityConceptIds = c(38003563),
    studyStartDate = 20190301,
    studyEndDate = 20241231,
    requiredDurationDays = 365,
    requiredDomains = c("condition", "drug"),
    desiredDomains = c("measurement", "observation"),
    requiredVisits = c("IP", "OP"),
    desiredVisits = c("ER"),
    targetName = "lisinopril",
    targetConceptIds = c(1308216, 40165015, 1310756, 1373928, 1331235, 1334456, 1335471, 1340128, 1341927, 1342001, 1343916, 1344965, 1345858, 1346823, 1347384, 1348840, 1350489, 1351557, 1353766, 1358359, 19078106, 19079251, 19080128, 19081375, 19082103, 19083462, 19084519, 19085647, 19086374, 19087523, 19088156, 19089374, 19090528, 19091647, 19092851, 19093742, 19094836, 19095127, 19096438, 19097521),
    comparatorName = "hydrochlorothiazide",
    comparatorConceptIds = c(974166, 978555, 974267, 975125, 976435, 977214, 978312, 979563, 980128, 981437, 982516, 983628, 984752, 985814, 986927, 987035, 988149, 989253, 990364, 991478, 19001254, 19002367, 19003481, 19004592, 19005706, 19006813, 19007925, 19008034, 19009148, 19010259, 19011367, 19012478, 19013582, 19014695, 19015801, 19016914, 19017028, 19018135, 19019247, 19020358),
    indicationName = "hypertension",
    indicationConceptIds = c(316866, 4028741, 320128, 321319, 314665, 315832, 316994, 318137, 319456, 320572, 321684, 322791, 323856, 324967, 325074, 326185, 327293, 328401, 329516, 330627, 4019977, 4021083, 4022194, 4023308, 4024415, 4025529, 4026634, 4027748, 4029853, 4030967, 4031074, 4032188, 4033295, 4034409, 4035514, 4036628, 4037735, 4038849, 4039954, 4040068),
    outcomeName = "myocardial_infarction",
    outcomeConceptIds = c(4329847, 312327, 434376, 438170, 438438, 439693, 441579, 442752, 443454, 444413, 4108217, 4108678, 4109049, 4109786, 4110192, 4110789, 4111414, 4112183, 4112853, 4113557, 4114195, 4114821, 4115462, 4116142, 4116798, 4117436, 4118097, 4118752, 4119398, 4120067, 4120718, 4121375, 4122014, 4122681, 4123347, 4123998, 4124652, 4125319, 4125987, 4126638, 4127294, 4127961, 4128619, 4129284, 4129938, 4130597, 4131265, 4131921, 4132579, 4133248),
    targetUseDrugEra = TRUE,
    comparatorUseDrugEra = TRUE
  ),
  list(
    analysisId = 2,
    analysisName = "Diabetes_Analysis",
    minAge = 30,
    maxAge = 75,
    genderConceptIds = c(8507, 8532),
    raceConceptIds = NULL,
    ethnicityConceptIds = NULL,
    studyStartDate = 20200101,
    studyEndDate = 20241231,
    requiredDurationDays = 180,
    requiredDomains = c("condition", "drug", "measurement"),
    desiredDomains = NULL,
    requiredVisits = c("OP"),
    desiredVisits = NULL,
    targetName = "metformin",
    targetConceptIds = c(1503297, 1503328, 1503476, 1503519, 1503684, 1503812, 1503945, 1504078, 1504213, 1504346, 1504479, 1504612, 1504745, 1504878, 1505011, 1505144, 1505277, 1505410, 1505543, 1505676, 19100128, 19100261, 19100394, 19100527, 19100660, 19100793, 19100926, 19101059, 19101192, 19101325),
    comparatorName = NULL,
    comparatorConceptIds = NULL,
    indicationName = "diabetes",
    indicationConceptIds = c(201820, 201826, 201254, 201387, 201519, 201652, 201785, 201918, 202051, 202184, 202317, 202450, 202583, 202716, 202849, 202982, 203115, 203248, 203381, 203514, 4016083, 4016216, 4016349, 4016482, 4016615, 4016748, 4016881, 4017014, 4017147, 4017280, 4017413, 4017546, 4017679, 4017812, 4017945),
    outcomeName = "myocardial_infarction",
    outcomeConceptIds = c(4329847, 312327, 434376, 438170, 438438, 439693, 441579, 442752, 443454, 444413, 4108217, 4108678, 4109049, 4109786, 4110192, 4110789, 4111414, 4112183, 4112853, 4113557, 4114195, 4114821, 4115462, 4116142, 4116798),
    targetUseDrugEra = FALSE,
    comparatorUseDrugEra = NULL
  ),
  list(
    analysisId = 3,
    analysisName = "ScaryAffliction_study",
    minAge = 0,
    maxAge = 150,
    genderConceptIds = c(8507),
    raceConceptIds = c(8515),
    ethnicityConceptIds = c(38003563),
    studyStartDate = NULL,
    studyEndDate = NULL,
    requiredDurationDays = 90,
    requiredDomains = c("condition"),
    desiredDomains = c("drug", "procedure"),
    requiredVisits = NULL,
    desiredVisits = c("IP", "ER"),
    targetName = "scary_drug",
    targetConceptIds = c(12345, 12478, 12611, 12744, 12877, 13010, 13143, 13276, 13409, 13542, 13675, 13808, 13941, 14074, 14207, 14340, 14473, 14606, 14739, 14872, 15005, 15138, 15271, 15404, 15537, 15670, 15803, 15936, 16069, 16202, 16335, 16468, 16601, 16734, 16867, 17000, 17133, 17266, 17399, 17532, 17665, 17798, 17931, 18064, 18197),
    comparatorName = "placebo",
    comparatorConceptIds = c(67890, 68023, 68156, 68289, 68422, 68555, 68688, 68821, 68954, 69087, 69220, 69353, 69486, 69619, 69752, 69885, 70018, 70151, 70284, 70417, 70550, 70683, 70816, 70949, 71082, 71215, 71348, 71481, 71614, 71747, 71880, 72013, 72146, 72279, 72412),
    indicationName = NULL,
    indicationConceptIds = NULL,
    outcomeName = "myocardial_infarction",
    outcomeConceptIds = c(4329847, 312327, 434376, 438170, 438438, 439693, 441579, 442752, 443454, 444413, 4108217, 4108678, 4109049, 4109786, 4110192),
    targetUseDrugEra = TRUE,
    comparatorUseDrugEra = FALSE
  )
)

userNotes <- list(
	list(
		analysisId = 1,
		text = "This analysis focuses on hypertension patients. We excluded patients with prior MI."
	),
	list(
		analysisId = 1,
		text = "This something focuses on hypertension patients. We excluded patients with prior MI."
	),
	list(
		analysisId = 2,
		text = "Diabetes cohort includes both Type 1 and Type 2. Consider splitting in future analyses."
	),
	list(
		analysisId = 3,
		text = "Preliminary analysis only. Needs review before final report."
	)
)


#Test

#createPdfReport(results = results, analysisSettings = analysisSettings,
#                file = "~/Desktop/db_diagnostics_results_test.pdf", userNotes = userNotes)
